name: Deploy to ECR

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag and push Docker imageand
      env:
        ECR_REGISTRY_URL: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_NAME: ${{ secrets.AWS_ECR_REPISTORY_NAME }}
        IMAGE_TAG: 1.0.0
      run: |
        docker build -t $ECR_REGISTRY_URL/$ECR_REPOSITORY_NAME:LATEST .
        docker push $ECR_REGISTRY_URL/$ECR_REPOSITORY_NAME:LATEST